app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', SolicitudListView.as_view(), name='solicitudes'),
    path('crear_solicitud/', SolicitudCreateView.as_view(), name='crear_solicitud'),
    path('crear_modelo/', crear_modelo, name='crear_modelo'),
    path('listar_modelos/', ModeloListView.as_view(), name='listarMod'),
    path('modelo/solicitudes/listar/<id>/', listar_solicitudes_de_modelo, name='solicitudModel'),
    path('editar/solicitud/<int:pk>/',SolicitudUpdateView.as_view(), name='solicitudEdit'),
    path('eliminar_solicitud/<id>/', eliminarSolicitud, name='solicitudDel'),
    path('eliminar_modelo/<id>/', eliminarModelo, name='modeloDel'),

    path('listar/modelos/cancelados/', ModeloCancelListView.as_view(), name='listarModCancel'),
    path('listar/modelos/archivados/', ModeloArchivedListView.as_view(), name='listarModArch'),

    path('modelo/pdf/<int:pk>/', ModeloPDFView.as_view(), name='modelo_pdf'),

    path('prueba/', prueba, name='prueba'),

    path('2022/', modelos2022, name='2022'),
]

solicitud_dietas/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('index/', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Unidad_Organizativa(models.Model):
    nombre=models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name="Unidad Organizativa"
        verbose_name_plural="Unidades Organizativas"
class Autoriza(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    cargo=models.CharField(max_length=150)
    dependencia=models.CharField(max_length=100)

    def __str__(self):
        return self.usuario.first_name+' '+self.usuario.last_name

class Cargo_al_Presupuesto(models.Model):
    cuenta=models.CharField(max_length=20)

    def __str__(self):
        return self.cuenta

class Trabajador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    ci=models.CharField(max_length=11, unique=True)

    def __str__(self):
            return self.usuario.first_name+' '+self.usuario.last_name

    class Meta:
        verbose_name = "Trabajador"
        verbose_name_plural = "Trabajadores"

class PARLEG(models.Model):
    trabajador=models.ForeignKey(Trabajador, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.trabajador.usuario.first_name+' '+self.trabajador.usuario.last_name

class Solicitante(models.Model):
    usuario=models.ForeignKey(User, on_delete=models.CASCADE)
    telf=models.CharField(max_length=100)
    cargo=models.CharField(max_length=100)
    unidad_organizativa=models.ForeignKey(Unidad_Organizativa, on_delete=models.CASCADE)
    def __str__(self):
        return self.usuario.first_name+' '+self.usuario.last_name

class Crea(models.Model):
    usuario=models.ForeignKey(User, on_delete=models.CASCADE)
    unidad_organizativa=models.ForeignKey(Unidad_Organizativa, on_delete=models.CASCADE)
    def __str__(self):
        return self.usuario.username

class C_Contable(models.Model):
    nombre=models.CharField(max_length=4)
    def __str__(self):
        return self.nombre

class Solicitud(models.Model):
    numero=models.IntegerField()
    solicitante=models.ForeignKey(Solicitante, on_delete=models.CASCADE)
    trabajador=models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    unidad_organizativa=models.ForeignKey(Unidad_Organizativa, on_delete=models.CASCADE)
    c_contable=models.ForeignKey(C_Contable, on_delete=models.CASCADE)
    provincia=models.CharField(max_length=50)
    origen=models.CharField(max_length=50)
    prov_destino=models.CharField(max_length=50)
    destino=models.CharField(max_length=50)
    regreso=models.CharField(max_length=50)
    fecha_inicio=models.DateField()
    fecha_final=models.DateField()
    #nuevos models add
    parleg=models.ForeignKey(Trabajador, on_delete=models.CASCADE, related_name='Trabajador_parleg', null=True, blank=True)
    cargo_presupuesto=models.ForeignKey(Cargo_al_Presupuesto, on_delete=models.CASCADE)
    autoriza=models.ForeignKey(Autoriza, on_delete=models.CASCADE)
    estado=models.CharField(max_length=200)
    observaciones=models.CharField(max_length=500, blank=True, null=True)
    labor=models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return str(self.numero)

    class Meta:
        verbose_name="Solicitud"
        verbose_name_plural="Solicitudes"

class Modelo(models.Model):
    nombre=models.CharField(max_length=50)
    solicitante=models.CharField(max_length=50)
    unidad_organizativa=models.CharField(max_length=100)
    c_contable=models.CharField(max_length=4)
    consec=models.IntegerField()
    solicitudes=models.ManyToManyField(Solicitud)
    parleg=models.CharField(max_length=200, blank=True, null=True)
    autoriza=models.CharField(max_length=50)
    cargo_presupuesto=models.CharField(max_length=20)
    observaciones = models.CharField(max_length=500, blank=True, null=True)
    estado=models.CharField(max_length=10)
    #campos nuevos del autoriza y el solicita
    cargo_autoriza=models.CharField(max_length=100)
    dependencia_autoriza=models.CharField(max_length=100)
    cargo_solicita=models.CharField(max_length=100)
    area_trabajo_solicita=models.CharField(max_length=100)
    labor=models.CharField(max_length=500, blank=True, null=True)
    fecha=models.DateField(default=date.today())

    def __str__(self):
        return self.nombre

    

app/templates/solicitudes/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block js %}

    <script>
        //Empieza el select dinamico

    var municipios_1=new Array("-","Artemisa","Guanajay","Caimito","Bauta","Castilla y León","Castilla-La Mancha","...");
    var municipios_2=new Array("-","Salta","San Juan","San Luis","La Rioja","La Pampa","...");
    var municipios_3=new Array("-","Cali","Santamarta","Medellin","Cartagena","...");
    var municipios_4=new Array("-","Aisne","Creuse","Dordogne","Essonne","Gironde ","...");
    var municipios_5=new Array("-","Cienfuegos","Creuse","Dordogne","Essonne","Gironde ","...");

    var todasMunicipios = [
    [],
    municipios_1,
    municipios_2,
    municipios_3,
    municipios_4,
    municipios_5,
    ];

  function cambia_provincia(){ 
   	//tomo el valor del select del pais elegido 
   	var pais 
   	pais = document.f1.provincia[document.f1.provincia.selectedIndex].value 
   	//miro a ver si el pais está definido 
   	if (pais != 0) { 
      	//si estaba definido, entonces coloco las opciones de la provincia correspondiente. 
      	//selecciono el array de provincia adecuado 
      	mis_municipios=todasMunicipios[pais]
      	//calculo el numero de provincias 
      	num_municipios = mis_municipios.length 
      	//marco el número de provincias en el select 
      	document.f1.origen.length = num_municipios 
      	document.f1.regreso.length = num_municipios 
      	//para cada provincia del array, la introduzco en el select 
      	for(i=0;i<num_municipios;i++){ 
         	document.f1.origen.options[i].value=mis_municipios[i] 
         	document.f1.regreso.options[i].value=mis_municipios[i] 
         	document.f1.origen.options[i].text=mis_municipios[i] 
         	document.f1.regreso.options[i].text=mis_municipios[i] 
      	}	
   	}else{ 
      	//si no había provincia seleccionada, elimino las provincias del select 
      	document.f1.origen.length = 1 
      	document.f1.regreso.length = 1 
      	//coloco un guión en la única opción que he dejado 
      	document.f1.origen.options[0].value = "-" 
      	document.f1.regreso.options[0].value = "-" 
      	document.f1.origen.options[0].text = "-" 
      	document.f1.regreso.options[0].text = "-" 
   	} 
   	//marco como seleccionada la opción primera de provincia 
   	document.f1.origen.options[0].selected = true 
   	document.f1.regreso.options[0].selected = true 
}

function cambia_provinciaDestino(){ 
   	//tomo el valor del select del pais elegido 
   	var pais 
   	pais = document.f1.prov_destino[document.f1.prov_destino.selectedIndex].value 
   	//miro a ver si el pais está definido 
   	if (pais != 0) { 
      	//si estaba definido, entonces coloco las opciones de la provincia correspondiente. 
      	//selecciono el array de provincia adecuado 
      	mis_municipios=todasMunicipios[pais]
      	//calculo el numero de provincias 
      	num_municipios = mis_municipios.length 
      	//marco el número de provincias en el select 
      	document.f1.destino.length = num_municipios
      	//para cada provincia del array, la introduzco en el select 
      	for(i=0;i<num_municipios;i++){ 
         	document.f1.destino.options[i].value=mis_municipios[i] 
         	document.f1.destino.options[i].text=mis_municipios[i] 
      	}	
   	}else{ 
      	//si no había provincia seleccionada, elimino las provincias del select 
      	document.f1.destino.length = 1
      	//coloco un guión en la única opción que he dejado 
      	document.f1.destino.options[0].value = "-" 
      	document.f1.destino.options[0].text = "-" 
   	} 
   	//marco como seleccionada la opción primera de provincia 
   	document.f1.destino.options[0].selected = true 
}
//Termina lo del select
         function generarModelo(){
            Swal.fire({
                "title": "Estas Seguro?",
                "icon": "question",
                "showCancelButton": true,
                "cancelButtonText": "No, Cancelar",
                "confirmButtonText": "Si, Generar el Modelo",
                "reverseButtons": true,
                "confirmButtonColor": "#178f13"
            })
            .then(function(result){
                if (result.isConfirmed){
                    window.location.href = "/crear_modelo/"
                }
            })
        }

        $('#fecha_inicio').datetimepicker({
            format: 'L'
        });
    </script>
{% endblock %}
{% block content %}
<form action="" method="post" id="" enctype="multipart/form-data">
    <div class="card card-default">
        <div class="card-body ">
            {% csrf_token %}

            <div class=" form-group form-card text-center">
                <div class="container">
                    <!---Aqui comienza a crear el formulario--->
<!--                    {{form | crispy}}-->
                    <div class="modal-content">
                        <div class="modal-header btn-primary" style="height: 2cm";>
		                    <h4 class="modal-title">{{title}}</h4>
	                    </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <!---Solicitante-->
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Solicita:</label>
                                            <div class="col-sm-5">
                                                {{form.solicitante}}
                                            </div>
                                    </div>
                                    <!---Fin Solicitante-->
                                    <!---Trabajador-->
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Trabajador:</label>
                                            <div class="col-sm-5">
                                                {{form.trabajador}}
                                            </div>
                                    </div>
                                    <!---Fin Trabajador-->
                                    <!---UO-->
                                    <div class="form-group row">
				                        <label class="col-sm-4 col-form-label">Unidad Organizativa:</label>
				                            <div class="col-sm-5">
                                                {{form.unidad_organizativa}}
                                            </div>
			                        </div>
                                    <!---Fin UO-->
                                    <!---Centro Contable-->
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Centro Contable:</label>
                                            <div class="col-sm-5">
                                                {{form.c_contable}}
                                            </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Con Cargo al Presupuesto:</label>
                                            <div class="col-sm-5">
                                                {{form.cargo_presupuesto}}
                                            </div>
                                    </div>
                                    <!---Fin Centro COntable-->
                                    <!---Provincia-->
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Provincia:</label>
				                            <div class="col-sm-5">
                                                {{form.provincia}}
                                            </div>
			                        </div>
                                    <!---Fin Provincia-->
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group row">
				                        <label class="col-sm-4 col-form-label">Origen:</label>
				                            <div class="col-sm-5">
                                                {{form.origen}}
                                            </div>
			                        </div>
                                    <div class="form-group row">
				                        <label class="col-sm-4 col-form-label">Destino:</label>
				                            <div class="col-sm-5">
                                                {{form.destino}}
                                            </div>
                                    </div>
                                    <div class="form-group row">
				                    <label class="col-sm-4 col-form-label">Regreso:</label>
				                        <div class="col-sm-5">
                                            {{form.regreso}}
                                        </div>
			                        </div>
                                    <div class="form-group row">
				                        <label class="col-sm-4 col-form-label">Fecha de Inicio:</label>
				                            <div class="col-sm-5">
					                            <div id="fecha_inicio" data-target-input="nearest" class="input-group date">
						                            {{form.fecha_inicio}}
						                                <div data-target="#fecha_inicio" data-toggle="datetimepicker" class="input-group-append">
							                                <div class="input-group-text"><i class="fa fa-calendar"></i>
							                                </div>
						                                </div>
					                            </div>
				                            </div>
			                        </div>
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Fecha Final:</label>
                                            <div class="col-sm-5">
                                                <div id="finaldate" data-target-input="nearest" class="input-group date">
                                                    {{form.fecha_final}}
                                                        <div data-target="#reservationdate" data-toggle="datetimepicker" class="input-group-append">
                                                            <div class="input-group-text"><i class="fa fa-calendar"></i>
                                                            </div>
                                                        </div>
                                                </div>
                                            </div>
			                        </div>
                                    <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Persona autorizada a Recibir y Loquidar el efectivo del grupo:</label>
                                            <div class="col-sm-5">
                                                {{form.parleg}}
                                            </div>
                                    </div>
                                </div>
                                <div class="form-group row">
                                        <label class="col-sm-4 col-form-label">Autoriza:</label>
				                            <div class="col-sm-4">
                                                {{form.autoriza}}
                                            </div>
			                        </div>
                            </div>
                            <div class="form-group row">
                                        <label class=" col-form-label">Observaciones:</label>
				                            <div class="">
                                                {{form.observaciones}}
                                            </div>
			                        </div>
                            {% if action == 'add' %}
                    <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Agregar
                    </button>
                            {% else %}
                    <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i> Editar
                    </button>
                            {% endif %}
                    </div>
                </div>

                </div>
            </div>

        </div>
    </div>
</form>
{% endblock %}

app/templates/solicitudes/listar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="row pl-5 pr-5 ml-5" >
         <div class="col-lg-3 col-6 ml-5">
            <div class="small-box bg-success">
                <div class="inner">
                    <h1 style="color: white;" class="text-center">
                        Solicitudes Aceptadas
                    </h1>
                </div>
                <div class="icon"><i class="fas fa-check-square"></i>
                </div>
                {% if perms.app.view_modelo %}
                <a href="{% url 'listarMod' %}" class="small-box-footer" style="color: white !important;">
                Ver listado <i class="fas fa-arrow-circle-right" style="color: white;"></i>
                </a>

                {% else %}
                <a href="#" class="small-box-footer" style="color: white !important;">
                No tiene permisos para ver los Modelos <i class="fas fa-eye-slash" style="color: white;"></i>
                </a>
                {% endif %}
            </div>
            </div>

        <div class="col-lg-3 col-6 ml-5">
            <div class="small-box btn-primary">
                <div class="inner">
                    <h1 style="color: white;" class="text-center">
                        Solicitudes Archivadas
                    </h1>
                </div>
                <div class="icon"><i class="fas fa-folder"></i>
                </div>
                {% if perms.app.view_modelo %}
                <a href="{% url 'listarModArch' %}" class="small-box-footer" style="color: white !important;">
                Ver listado <i class="fas fa-arrow-circle-right" style="color: white;"></i>
                </a>

                {% else %}
                <a href="#" class="small-box-footer" style="color: white !important;">
                No tiene permisos para ver los Modelos <i class="fas fa-eye-slash" style="color: white;"></i>
                </a>
                {% endif %}
            </div>
            </div>

        <div class="col-lg-3 col-6 ml-5">
        <div class="small-box bg-danger">
                <div class="inner">
                    <h1 style="color: white;" class="text-center">
                        Solicitudes Canceladas
                    </h1>
                </div>
                <div class="icon"><i class="fas fa-times-circle"></i>
                </div>
                {% if perms.app.view_modelo %}
                <a href="{% url 'listarModCancel' %}" class="small-box-footer" style="color: white !important;">
                Ver listado <i class="fas fa-arrow-circle-right" style="color: white;"></i>
                </a>

                {% else %}
                <a href="#" class="small-box-footer" style="color: white !important;">
                No tiene permisos para ver los Modelos <i class="fas fa-eye-slash" style="color: white;"></i>
                </a>
                {% endif %}
            </div>

        <div class="col-lg-4 col-6"></div>
            </div>
             
        </div>
    </div>
    <div class=" card card-default">
   
        <div class="card-header px-3 mb-3 mt-3 container">
            <h3 class="card-title">
            <i class="fas fa-search"></i>
                Listado de las Solicitudes de Dietas
            </h3>
            </div>
        <div class="card card-body content-header mx-5 px-5">
         {% if perms.app.add_solicitud %}
             <div class=" card-footer mt-3">
            <a href="{% url 'crear_solicitud' %}" type="button" class="btn btn-primary">
                <i class="fas fa-plus"></i>
                Agregar Solicitud
            </a>
        </div>
             {% endif %}
            <table id="myTable" class="display" style="width: 100%;">
                <thead>
                    <tr>
                        <th>Nombre y Apellidos</th>
                        <th>Carnet de Identidad</th>
                        <th>Unidad Organizativa</th>
                        <th>C. Contable que entrega el anticipio</th>
                        <th>Origen</th>
                        <th>Destino</th>
                        <th>Regreso</th>
                        <th>Desde</th>
                        <th>Hasta</th>
                        <th>Estado</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in object_list %}
                    <tr>
                        <td style="width: 150px;">{{i.trabajador}}</td>
                        <td>{{i.trabajador.ci}}</td>
                        <td>{{i.unidad_organizativa}}</td>
                        <td style="width: 80px;">{{i.c_contable}}</td>
                        <td>{{i.origen}}</td>
                        <td>{{i.destino}}</td>
                        <td>{{i.regreso}}</td>
                        <td>{{i.fecha_inicio}}</td>
                        <td>{{i.fecha_final}}</td>
                        <td>{{i.estado}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}