app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', SolicitudListView.as_view(), name='solicitudes'),
    path('crear_solicitud/', SolicitudCreateView.as_view(), name='crear_solicitud'),
    path('crear_modelo/', crear_modelo, name='crear_modelo'),
    path('listar_modelos/', ModeloListView.as_view(), name='listarMod'),
    path('modelo/solicitudes/listar/<id>/', listar_solicitudes_de_modelo, name='solicitudModel'),
    path('editar/solicitud/<int:pk>/',SolicitudUpdateView.as_view(), name='solicitudEdit'),
    path('eliminar_solicitud/<id>/', eliminarSolicitud, name='solicitudDel'),
    path('eliminar_modelo/<id>/', eliminarModelo, name='modeloDel'),

    path('listar/modelos/cancelados/', ModeloCancelListView.as_view(), name='listarModCancel'),
    path('listar/modelos/archivados/', ModeloArchivedListView.as_view(), name='listarModArch'),

    path('modelo/pdf/<int:pk>/', ModeloPDFView.as_view(), name='modelo_pdf'),

    path('prueba/', prueba, name='prueba'),

    path('2022/', modelos2022, name='2022'),
]

solicitud_dietas/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('index/', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Unidad_Organizativa(models.Model):
    nombre=models.CharField(max_length=100)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name="Unidad Organizativa"
        verbose_name_plural="Unidades Organizativas"
class Autoriza(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    cargo=models.CharField(max_length=150)
    dependencia=models.CharField(max_length=100)

    def __str__(self):
        return self.usuario.first_name+' '+self.usuario.last_name

class Cargo_al_Presupuesto(models.Model):
    cuenta=models.CharField(max_length=20)

    def __str__(self):
        return self.cuenta

class Trabajador(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    ci=models.CharField(max_length=11, unique=True)

    def __str__(self):
            return self.usuario.first_name+' '+self.usuario.last_name

    class Meta:
        verbose_name = "Trabajador"
        verbose_name_plural = "Trabajadores"

class PARLEG(models.Model):
    trabajador=models.ForeignKey(Trabajador, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.trabajador.usuario.first_name+' '+self.trabajador.usuario.last_name

class Solicitante(models.Model):
    usuario=models.ForeignKey(User, on_delete=models.CASCADE)
    telf=models.CharField(max_length=100)
    cargo=models.CharField(max_length=100)
    unidad_organizativa=models.ForeignKey(Unidad_Organizativa, on_delete=models.CASCADE)
    def __str__(self):
        return self.usuario.first_name+' '+self.usuario.last_name

class Crea(models.Model):
    usuario=models.ForeignKey(User, on_delete=models.CASCADE)
    unidad_organizativa=models.ForeignKey(Unidad_Organizativa, on_delete=models.CASCADE)
    def __str__(self):
        return self.usuario.username

class C_Contable(models.Model):
    nombre=models.CharField(max_length=4)
    def __str__(self):
        return self.nombre

class Solicitud(models.Model):
    numero=models.IntegerField()
    solicitante=models.ForeignKey(Solicitante, on_delete=models.CASCADE)
    trabajador=models.ForeignKey(Trabajador, on_delete=models.CASCADE)
    unidad_organizativa=models.ForeignKey(Unidad_Organizativa, on_delete=models.CASCADE)
    c_contable=models.ForeignKey(C_Contable, on_delete=models.CASCADE)
    provincia=models.CharField(max_length=50)
    origen=models.CharField(max_length=50)
    prov_destino=models.CharField(max_length=50)
    destino=models.CharField(max_length=50)
    regreso=models.CharField(max_length=50)
    fecha_inicio=models.DateField()
    fecha_final=models.DateField()
    #nuevos models add
    parleg=models.ForeignKey(Trabajador, on_delete=models.CASCADE, related_name='Trabajador_parleg', null=True, blank=True)
    cargo_presupuesto=models.ForeignKey(Cargo_al_Presupuesto, on_delete=models.CASCADE)
    autoriza=models.ForeignKey(Autoriza, on_delete=models.CASCADE)
    estado=models.CharField(max_length=200)
    observaciones=models.CharField(max_length=500, blank=True, null=True)
    labor=models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return str(self.numero)

    class Meta:
        verbose_name="Solicitud"
        verbose_name_plural="Solicitudes"

class Modelo(models.Model):
    nombre=models.CharField(max_length=50)
    solicitante=models.CharField(max_length=50)
    unidad_organizativa=models.CharField(max_length=100)
    c_contable=models.CharField(max_length=4)
    consec=models.IntegerField()
    solicitudes=models.ManyToManyField(Solicitud)
    parleg=models.CharField(max_length=200, blank=True, null=True)
    autoriza=models.CharField(max_length=50)
    cargo_presupuesto=models.CharField(max_length=20)
    observaciones = models.CharField(max_length=500, blank=True, null=True)
    estado=models.CharField(max_length=10)
    #campos nuevos del autoriza y el solicita
    cargo_autoriza=models.CharField(max_length=100)
    dependencia_autoriza=models.CharField(max_length=100)
    cargo_solicita=models.CharField(max_length=100)
    area_trabajo_solicita=models.CharField(max_length=100)
    labor=models.CharField(max_length=500, blank=True, null=True)
    fecha=models.DateField(default=date.today())

    def __str__(self):
        return self.nombre

    

app/templates/modelos/antiguos/listar.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class=" card card-default">
        <div class="card-header px-3 mb-3 mt-3 container">
            <h3 class="card-title">
            <i class="fas fa-search"></i>
                Listado de los Modelos
            </h3>
            </div>
        <div class="card card-body content-header mx-5 px-5">
            <table id="myTable" class="display" style="width: 100%;">
                <thead>
                    <tr>
                        <th>Ver</th>
                        <th style="width: 2cm">Cons</th>
                        <th>Creador</th>
                        <th>Solicitante</th>
                        <th>Unidad Organizativa</th>
                        <th>Centro Contable</th>
                        <th>Cargo al Presupuesto</th>
                        <th>Autoriza</th>
                        <th>Observaciones</th>
                        <th style="width: 3cm">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in archivados %}
                    <tr>
                        <td style="width: 1cm"></td>
                        <td style="width: 20px;">2022{{i.consec}}</td>
                        <td style="width: 150px;">{{i.nombre}}</td>
                        <td style="width: 150px;">{{i.solicitante}}</td>
                        <td style="width: 150px;">{{i.unidad_organizativa}}</td>
                        <td style="width: 150px;"><div class="pl-5">{{i.c_contable}}</div></td>
                        <td>{{i.cargo_presupuesto}}</td>
                        <td>{{i.autoriza}}</td>
                        <td>{{i.observaciones}}</td>
                        <td>
                <!-- {% if perms.app.view_modelo %}
                <a href="{% url 'modelo_pdf' i.id %}" type="button" class="btn btn-success">
                    <i class="fas fa-download"></i>
                </a>
                {% endif %} -->
<!--                <a href="{% url 'solicitudModel' i.id%}" type="button" class="btn btn-warning">-->
<!--                    <i class="fas fa-edit"></i>-->
<!--                </a>-->
{% if perms.app.view_modelo %}
<a href="{% url 'solicitudModel' i.id%}" type="button" class="btn btn-warning">
    <i class="fas fa-eye"></i>
</a>
{% endif %}
                {% if perms.app.delete_modelo %}
                <a href="#" onclick="eliminarModelo({{i.id}})" type="button" class="btn btn-danger">
                    <i class="fas fa-times-circle"></i>
                </a>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}